apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-apps-secrets-sa
  namespace: apps
  annotations:
    iam.gke.io/gcp-service-account: k8s-secrets-sa@storied-cider-400415.iam.gserviceaccount.com